import { AppError } from '../../../shared/errors/basic-app-error';
import { AppErrorCode } from '../../../shared/errors/error-codes';

export class AppGoogleOAuthCodeMissingException extends AppError {
  constructor() {
    super(AppErrorCode.BAD_REQUEST, 400, 'Google OAuth callback code is required');
  }
}

export class AppGoogleOAuthInvalidStateException extends AppError {
  constructor(message = 'Google OAuth state is invalid or expired') {
    super(AppErrorCode.BAD_REQUEST, 400, message, [
      'Pass a valid state generated by GET /auth/google.',
      'State is used to bind deviceId with callback and prevent tampering.',
    ]);
  }
}

export class AppGoogleOAuthProviderRejectedException extends AppError {
  constructor() {
    super(AppErrorCode.UNAUTHORIZED, 401, 'Google OAuth authorization was rejected by provider');
  }
}

export class AppGoogleOAuthTokenExchangeException extends AppError {
  constructor() {
    super(AppErrorCode.UNAUTHORIZED, 401, 'Failed to exchange Google OAuth code for tokens', [
      'Authorization code may be expired or already used.',
      'Check GOOGLE_OAUTH_CLIENT_ID, GOOGLE_OAUTH_CLIENT_SECRET and GOOGLE_OAUTH_CALLBACK_URL.',
    ]);
  }
}

export class AppGoogleOAuthUserInfoFetchException extends AppError {
  constructor() {
    super(AppErrorCode.UNAUTHORIZED, 401, 'Failed to fetch Google user profile');
  }
}

export class AppGoogleOAuthEmailMissingException extends AppError {
  constructor() {
    super(AppErrorCode.BAD_REQUEST, 400, 'Google account email is missing', ['Ensure OAuth scope contains email.']);
  }
}

export class AppGoogleOAuthProviderIdMissingException extends AppError {
  constructor() {
    super(AppErrorCode.BAD_REQUEST, 400, 'Google account identifier is missing');
  }
}

export class AppGoogleOAuthAccountConflictException extends AppError {
  constructor(message = 'Google OAuth account conflict') {
    super(AppErrorCode.CONFLICT, 409, message);
  }
}
