CREATE TYPE "user_roles" AS ENUM (
  'user',
  'admin',
  'moderator'
);

CREATE TYPE "auth_providers" AS ENUM (
  'google',
  'github'
);

CREATE TYPE "post_statuses" AS ENUM (
  'draft',
  'pending_review',
  'approved',
  'rejected',
  'blocked',
  'archived',
  'completed'
);

CREATE TYPE "post_review_statuses" AS ENUM (
  'pending',
  'approved',
  'rejected'
);

CREATE TYPE "currencies" AS ENUM (
  'uah'
);

CREATE TYPE "payment_statuses" AS ENUM (
  'pending',
  'success',
  'failed',
  'expired'
);

CREATE TYPE "payment_providers" AS ENUM (
  'wayforpay'
);

CREATE TYPE "comment_statuses" AS ENUM (
  'VISIBLE',
  'DELETED'
);

CREATE TYPE "file_providers" AS ENUM (
  'cloudinary'
);

CREATE TYPE "chat_types" AS ENUM (
  'private',
  'group',
  'post'
);

CREATE TABLE "users" (
  "id" uuid PRIMARY KEY,
  "email" varchar(255) UNIQUE,
  "name" varchar(128),
  "password" varchar,
  "photo_url" varchar(512),
  "role" user_roles,
  "is_active" boolean,
  "is_email_verified" boolean,
  "created_by_admin" boolean,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "provider_accounts" (
  "id" uuid PRIMARY KEY,
  "provider" auth_providers,
  "provider_id" varchar(255),
  "user_id" uuid,
  "provider_data" json,
  "access_token" varchar(512),
  "refresh_token" varchar(512),
  "token_expires_at" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "sessions" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid,
  "refresh_token_hash" varchar(255),
  "device_id" varchar(255),
  "user_agent" varchar(512),
  "ip" varchar(45),
  "last_used_at" timestamp,
  "expires_at" timestamp,
  "created_at" timestamp
);

CREATE TABLE "user_role_periods" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(128),
  "user_id" uuid,
  "role" user_roles,
  "start_date" timestamp,
  "end_date" timestamp,
  "changed_by_id" uuid,
  "created_at" timestamp
);

CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255),
  "content" text,
  "target_amount" decimal,
  "current_amount" decimal,
  "currency" currencies,
  "reference_payment_id" varchar(255) UNIQUE,
  "target_date" timestamp,
  "status" post_statuses,
  "status_reason" text,
  "author_id" uuid,
  "total_comments" int,
  "total_likes" int,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "payments" (
  "id" uuid PRIMARY KEY,
  "post_id" int,
  "user_id" uuid,
  "amount" decimal,
  "currency" currencies,
  "status" payment_statuses,
  "status_reason" text,
  "reference_payment_id" varchar(255),
  "last_attempt_id" uuid,
  "confirmed_at" timestamp,
  "expired_at" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "payment_attempts" (
  "id" uuid PRIMARY KEY,
  "payment_id" uuid,
  "provider" payment_providers,
  "provider_payment_id" varchar(255),
  "status" payment_statuses,
  "provider_response" json,
  "status_reason" text,
  "created_at" timestamp
);

CREATE TABLE "post_reviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int,
  "reviewed_by_id" uuid,
  "status" post_review_statuses,
  "is_active" boolean,
  "review_reason" text,
  "created_at" timestamp
);

CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int,
  "author_id" uuid,
  "content" text,
  "status" comment_statuses,
  "total_likes" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "comment_likes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "comment_id" int,
  "user_id" uuid,
  "created_at" timestamp
);

CREATE TABLE "post_likes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int,
  "user_id" uuid,
  "created_at" timestamp
);

CREATE TABLE "post_files" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar(512),
  "post_id" int,
  "uploaded_by_id" uuid,
  "storage_key" varchar(255),
  "provider" file_providers,
  "mime_type" varchar(255),
  "main_image" boolean,
  "size" int,
  "metadata" json,
  "original_name" varchar(255),
  "created_at" timestamp
);

CREATE TABLE "chats" (
  "id" uuid PRIMARY KEY,
  "type" chat_types,
  "title" varchar(255),
  "post_id" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "private_chats" (
  "id" uuid PRIMARY KEY,
  "chat_id" uuid UNIQUE,
  "user1_id" uuid,
  "user2_id" uuid,
  "created_at" timestamp
);

CREATE TABLE "chat_members" (
  "id" uuid PRIMARY KEY,
  "chat_id" uuid,
  "user_id" uuid,
  "joined_at" timestamp
);

CREATE TABLE "messages" (
  "id" uuid PRIMARY KEY,
  "chat_id" uuid,
  "sender_id" uuid,
  "content" text,
  "is_deleted" boolean,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "message_files" (
  "id" uuid PRIMARY KEY,
  "message_id" uuid,
  "url" varchar(512),
  "storage_key" varchar(255),
  "provider" file_providers,
  "mime_type" varchar(255),
  "size" int,
  "original_name" varchar(255),
  "created_at" timestamp
);

CREATE UNIQUE INDEX ON "provider_accounts" ("provider", "provider_id");

CREATE UNIQUE INDEX ON "sessions" ("user_id", "device_id");

CREATE UNIQUE INDEX ON "payment_attempts" ("provider", "provider_payment_id");

CREATE UNIQUE INDEX ON "comment_likes" ("comment_id", "user_id");

CREATE UNIQUE INDEX ON "post_likes" ("post_id", "user_id");

CREATE UNIQUE INDEX ON "private_chats" ("user1_id", "user2_id");

CREATE UNIQUE INDEX ON "chat_members" ("chat_id", "user_id");

ALTER TABLE "provider_accounts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_role_periods" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "posts" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("last_attempt_id") REFERENCES "payment_attempts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payment_attempts" ADD FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_reviews" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_reviews" ADD FOREIGN KEY ("reviewed_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comment_likes" ADD FOREIGN KEY ("comment_id") REFERENCES "comments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comment_likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_likes" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_files" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chats" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "private_chats" ADD FOREIGN KEY ("chat_id") REFERENCES "chats" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "private_chats" ADD FOREIGN KEY ("user1_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "private_chats" ADD FOREIGN KEY ("user2_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chat_members" ADD FOREIGN KEY ("chat_id") REFERENCES "chats" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chat_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "messages" ADD FOREIGN KEY ("chat_id") REFERENCES "chats" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "message_files" ADD FOREIGN KEY ("message_id") REFERENCES "messages" ("id") DEFERRABLE INITIALLY IMMEDIATE;
