import { AppError } from '../../../../shared/errors/basic-app-error';
import { AppErrorCode } from '../../../../shared/errors/error-codes';

export class AppOAuthCodeMissingException extends AppError {
  constructor(provider: string) {
    super(AppErrorCode.BAD_REQUEST, 400, `${provider} OAuth callback code is required`);
  }
}

export class AppOAuthInvalidStateException extends AppError {
  constructor(message = 'OAuth state is invalid or expired') {
    super(AppErrorCode.BAD_REQUEST, 400, message, [
      'Pass a valid state generated by GET /auth/:provider.',
      'State is used to bind deviceId with callback and prevent tampering.',
    ]);
  }
}

export class AppOAuthProviderRejectedException extends AppError {
  constructor(provider: string) {
    super(AppErrorCode.UNAUTHORIZED, 401, `${provider} OAuth authorization was rejected by provider`);
  }
}

export class AppOAuthTokenExchangeException extends AppError {
  constructor(provider: string) {
    super(AppErrorCode.UNAUTHORIZED, 401, `Failed to exchange ${provider} OAuth code for tokens`, [
      'Authorization code may be expired or already used.',
      `Check ${provider.toUpperCase()}_OAUTH_CLIENT_ID, CLIENT_SECRET and CALLBACK_URL.`,
    ]);
  }
}

export class AppOAuthUserInfoFetchException extends AppError {
  constructor(provider: string) {
    super(AppErrorCode.UNAUTHORIZED, 401, `Failed to fetch ${provider} user profile`);
  }
}

export class AppOAuthEmailMissingException extends AppError {
  constructor(provider: string) {
    super(AppErrorCode.BAD_REQUEST, 400, `${provider} account email is missing`, [
      'Ensure OAuth scope contains email.',
    ]);
  }
}

export class AppOAuthProviderIdMissingException extends AppError {
  constructor(provider: string) {
    super(AppErrorCode.BAD_REQUEST, 400, `${provider} account identifier is missing`);
  }
}

export class AppOAuthAccountConflictException extends AppError {
  constructor(message = 'OAuth account conflict') {
    super(AppErrorCode.CONFLICT, 409, message);
  }
}

export class AppOAuthAccountInactiveException extends AppError {
  constructor() {
    super(AppErrorCode.FORBIDDEN, 403, 'Your account is inactive');
  }
}

export class AppOAuthUnsupportedProviderException extends AppError {
  constructor(provider: string) {
    super(AppErrorCode.BAD_REQUEST, 400, `OAuth provider "${provider}" is not supported`);
  }
}
